# Make a copy of this file, replace corresponding paths, and don't push you config every time
verbose: false
log_dir: "./logs/"
encoder_type: conv
decoder_type: deconv

############# Audio ############
sampling_rate: 16000 # Sampling rate
res_type: 'kaiser_fast' # Resampling algorithm
top_db: 20 # The threshold (in decibels) below reference to consider as silence
length: 7680
##################################

############# Mu-law ############
quantize: 256
##################################

############# Training ############
learning_rate: 0.0002
train_val_split: 0.8
num_epochs: 35
batch_size: 32
use_cuda: false
use_speaker_conditioning: True
record_codebook_stats: False
record_gradient_stats: False
normalize: true
normalizer_path: "./data/vctk/vctk-mfcc-stats.pickle"
vctk_path: "./data/vctk"
log_period: 1
checkpoint_period: 1
features_path: 'features'
##################################

############# Encoder ############
num_hiddens: 768
input_dim: 256
##################################

############# VQ ############
# The higher this value, the higher the capacity in the information bottleneck.
num_embeddings: 44
# This value is not that important, usually 64 works. This will not change the capacity in the information-bottleneck.
embedding_dim: 64
commitment_cost: 0.25
##################################

############# Residual ############
residual_channels: 768
num_residual_layers: 2
##################################

############# Conv ############
use_kaiming_normal: false
##################################

############# Jitter ############
jitter_probability: 0.12
use_jitter: False
##################################


############# Features ############
input_features_type: mfcc
output_features_type: mfcc
input_features_dim: 47
input_features_filters: 13
output_features_dim: 47
output_features_filters: 13
augment_input_features: true
augment_output_features: true
##################################

eval:
  pretrained_weights_path: ./logs/21-07-17-185456-182711/checkpts/m_21.pth